FROM ubuntu:20.04

MAINTAINER CodeReady Containers

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && apt-get install -y libvirt-dev curl git gcc make golang
ENV PATH=/usr/sbin:/usr/bin:/sbin:/bin:/go/bin

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /go/bin v1.30.0

COPY . /go/src/github.com/code-ready/machine-driver-libvirt
WORKDIR /go/src/github.com/code-ready/machine-driver-libvirt

RUN make validate
RUN go build -i -v -ldflags="-s -w" -o /go/bin/crc-driver-libvirt ./cmd/machine-driver-libvirt
